/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const IndexNodeIdEditLazyImport = createFileRoute('/index/$nodeId/edit')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const IndexNodeIdEditLazyRoute = IndexNodeIdEditLazyImport.update({
  id: '/index/$nodeId/edit',
  path: '/index/$nodeId/edit',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/index.$nodeId.edit.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/index/$nodeId/edit': {
      id: '/index/$nodeId/edit'
      path: '/index/$nodeId/edit'
      fullPath: '/index/$nodeId/edit'
      preLoaderRoute: typeof IndexNodeIdEditLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/index/$nodeId/edit': typeof IndexNodeIdEditLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/index/$nodeId/edit': typeof IndexNodeIdEditLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/index/$nodeId/edit': typeof IndexNodeIdEditLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/index/$nodeId/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/index/$nodeId/edit'
  id: '__root__' | '/' | '/index/$nodeId/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  IndexNodeIdEditLazyRoute: typeof IndexNodeIdEditLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  IndexNodeIdEditLazyRoute: IndexNodeIdEditLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/index/$nodeId/edit"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/index/$nodeId/edit": {
      "filePath": "index.$nodeId.edit.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
